 Map<String, String> en =
 {
  // english language

   "Welcome_Back":"Welcome Back!",
   "Please_sign_in_to_continue.":"Please sign in to continue.",
   "Email":"Email",
   "Please_enter_your_email_address":"Please enter your email address",
   "Password":"Password",
   "Password_is_required":"Password is required",
   "LOGIN SUCCESSFULLY":"LOGIN SUCCESSFULLY",
   "Dont_have_an_account?":"Don\'t have an account?",
   "Sign_Up":"Sign Up",
   "Welcome_to":"Welcome to",
   "Sign_Up":"Sign Up",
   "Account_created_successfully":"Account created successfully",
   "Already_have_an_account?":"Already have an account? ",
   "LogIn":"LogIn",
   "Next_Question!":"Next Question!",
   "Next_Question":"Next Question",
   "Time_out!":"Time out!",
   "How_many_circles_do_you_see":"How many circles do you see?",
   "Count_forward_in_steps_of_5":"Count forward in steps of 5",
   "Count_forward_in_steps_of_10.":"Count forward in steps of 10.",
   "Count_backwards_in_steps_of_10_from_the_number_42":"Count backwards in steps of 10 from the number 42",
   "Count_forward_from_9_What_comes_next?":"Count forward from 9.What comes next?",
   "Count_backward_from_12_What_comes_next?":"Count backward from 12.What comes next?",
   "Count_forward_from_the_number_66":"Count forward from the number 66.",
   "Count_backward_from_the_number_100":"Count backward from the number 100.",
   "Count_forward_in_steps_of_two_from_8":"Count forward in steps of two from 8",
   "Count_backwards_in_steps_of_two_from_14":"Count backwards in steps of two from 14.",
   "Count_forward_in_steps_of_two_from_36":"Count forward in steps of two from 36",
   "Count_backwards_in_steps_of_two_from_72":"Count backwards in steps of two from 72.",
   "Test_Completed":"Test Completed",
   "How_many_points_do_you_see":"How many points do you see?",
   "complete_the_diagnostic":"Thank you for completing the Diagnostic. Below is a list of exercises that will help you improve in areas where you need a bit of help.\n\nExercises:",
   "Share":"Share",
   "Report":"Report",
   "Solve":"Solve",
   "How_many_are_missing_until_10":"How many are missing until 10?",
   "How_many_are_missing_until_20":"How many are missing until 20?",
  "While_counting_what_number_comes_after":"While counting, what number comes after",
  "While_counting_what_number_comes_before":"While counting what number comes before",
  "What_is_the_answer_to_one_plus_5?":"What is the answer to one plus 5?",
  "What_is_the_answer_to_5_plus_4?":"What is the answer to 5 plus 4?",
  "answer_to_eight_minus":"What is the answer to eight minus 5?",
  "add_to_5_make_eight":"What do I have to add to 5 to make eight? What needs to go in the gap?",
  "what_plus_two_is_seven":"What plus two is seven? What has to go in the gap?",
  "Select":"Select",
  "add_interactive_exercises":"As Numeris grows, we will add interactive exercises to help you practice.",
  "Child_Added":"Child Added",
  "New_Child":"New Child",
  "Select_Existing":"Select Existing",
  "Select_Child_Name":"Select Child Name",
  "Select_Child_Name":"Select Child Name",
  "Feature_not_available":"Feature not available",
  "Practise":"Practise",
  "Child_Selected":"Child Selected",
  "Enter_Name":"Enter Name",
  "What_is_the_double_of":"What is the double of",
  "What_is_the_half_of":"What is the half of",
  "ask_you_parents_or_your_teacher_to_checkk_the_website":"Ask you parents or your teacher to check the website for an explanation of how these exercises can be done. As Numeris grows, we will add interactive exercises to help you practice.",
  "diagnostic":"diagnostisch",
  "Start":"Start",
  "Start_diagnostic":"Start \ndiagnostic",
  "Together_the_two_dice_show":"Together, the two dice show",
  "what_could_the_number_on_the_dice_be":"What could the numbers on the dice be?",
  "Sign_In":"SignIn",
};