 Map<String, String> german =
 {
  // english language

   "Welcome_Back":"Willkommen zurück!",
   "Please_sign_in_to_continue.":"Bitte einloggen, um fortzufahren.",
   "Email":"Email",
   "Please_enter_your_email_address":"Geben Sie bitte Ihre Email-Adresse ein",
   "Password":"Passwort",
   "Password_is_required":"Passwort wird benötigt",
   "LOGIN_SUCCESSFULLY":"ANMELDUNG ERFOLGREICH",
   "Dont_have_an_account?":"Sie haben noch kein Konto?",

   "Welcome_to":"Willkommen zu",
   "Sign_Up":"Anmeldung",
   "Account_created_successfully":"Konto erfolgreich erstellt",
   "Already_have_an_account? ":"Sie haben bereits ein Konto? ",
   "LogIn":"Anmeldung",
   "Next_Question!":"Nächste Frage!",
   "Next_Question":"Nächste Frage",
   "Time_out!":"Auszeit!",
   "How_many_circles_do_you_see":"Wie viele kreise siehst du?",
   "Count_forward_in_steps_of_5":"Zähle in Fünfer Schritten von 5 aus weiter, bis ich ‚stopp‘ sage!",
   "Count_forward_in_steps_of_10.":"Zähle in Zehner Schritten von 10 aus weiter, bis ich ‚stopp‘ sage!",
   "Count_backwards_in_steps_of_10_from_the_number_42":"Zähle in Zehner Schritten von 42 aus zurück, bis ich ‚stopp‘ sage!",
   "Count_forward_from_9.What_comes_next?":"Zählen Sie ab 9 vorwärts. Was kommt als nächstes?",
   "Count_backward_from_12.What_comes_next?":"Von 12 an rückwärts zählen. Was kommt als nächstes?",
   "Count_forward_from_the_number_66.":"Zähle in Einer-Schritten vorwärts!",
   "Count_backward_from_the_number_100.":"Welche Zahl kommt beim Zählen nach der 10?",
   "Count_forward_in_steps_of_two_from_8":"Zähle in Zweierschritten von 8 aus weiter!",
   "Count_backwards_in_steps_of_two_from_14.":"Zähle in Zweierschritten von 14 aus zurück!.",
   "Count_forward_in_steps_of_two_from_36":"Zähle in Zweierschritten von 36 aus weiter!",
   "Count_backwards_in_steps_of_two_from_72.":"Zähle in Zweierschritten von 72 aus zurück!.",
   "Test_Completed":"Test abgeschlossen",
   "How_many_points_do_you_see?":"Wie viele Punkte sehen Sie?",
   "complete_the_diagnostic":"Vielen Dank, dass Sie die Diagnose abgeschlossen haben. Nachfolgend finden Sie eine Liste von Übungen, die Ihnen dabei helfen, sich in Bereichen zu verbessern, in denen Sie etwas Hilfe benötigen.\n\nÜbungen:",
   "Share":"Aktie",
   "Report":"Bericht",
   "Solve":"Lösen",
   "How_many_are_missing_until_10?":"Wie viele fehlen bis 10",
   "How_many_are_missing_until_20?":"Wie viele fehlen bis 20",
  "While_counting_what_number_comes_after":"Welche Zahl kommt beim Zählen nach der 10?",
  "While_counting_what_number_comes_before":"Welche Zahl kommt beim Zählen vor der 10?",
  "What_is_the_answer_to_one_plus_5?":"Eins plus 5 ist gleich was?",
  "What_is_the_answer_to_5_plus_4?":"Fünf plus 4 ist gleich was?",
  "answer_to_eight_minus":"Acht minus 5 ist gleich was?",
  "add_to_5_make_eight":"Fünf plus was ist acht? Was muss in die Lücke?",
  "what_plus_two_is_seven":"Was plus zwei ist sieben? Was muss in die Lücke?",
  "Select":"Wählen",
  "add_interactive_exercises":"Wenn Numeris wächst, werden wir interaktive Übungen hinzufügen, die Ihnen beim Üben helfen.",
  "Child_Added":"Kind hinzugefügt",
  "New_Child":"Neues Kind",
  "Select_Existing":"Wählen Sie Vorhanden aus",
  "Select_Child_Name":"Wählen Sie den Namen des Kindes aus",
  "Select_Child_Name":"Wählen Sie den Namen des Kindes aus",
  "Feature_not_available":"Funktion nicht verfügbare",
  "Practise":"Üben",
  "Child_Selected":"Kind ausgewählt",
  "Enter_Name":"Name eingeben",  
  "What_is_the_double_of":"Was is das Doppelte von",
  "What_is_the_half_of":"Was ist die Hälfte davon?",
   "ask_you_parents_or_your_teacher_to_checkk_the_website":"Bitten Sie Ihre Eltern oder Ihren Lehrer, auf der Website nach einer Erklärung zu suchen, wie diese Übungen durchgeführt werden können. Wenn Numeris wächst, werden wir interaktive Übungen hinzufügen, die Ihnen beim Üben helfen.",

  "Start_diagnostic":"Starten Sie \ndiagnostisch",

};